import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      "shop": "Shop",
      "about_us": "About Us",
      "blog": "Blog",
      "contacts": "Contacts",
      "home": "Home",
      "read_all_stories": "Read all stories",
      "more_articles": "More articles",
      "loading": "Loading...",
      "not_found": "Not found",
      "about_hero": "We're revolutionizing agriculture with vertical farming technology, bringing you the freshest, healthiest vegetables while protecting our planet.",
      "philosophy": "Philosophy",
      "about_philosophy": "Let's make the world healthier together. At Skycrops, we believe it's our responsibility to provide fresh, living vegetables while protecting our environment. That's why we're proud to introduce our revolutionary vertical farming technology - every time you buy our premium vegetables, you help create a more sustainable future!",
      "readArticle": "Read article",
      "noArticles": "No articles available at the moment.",
      "checkBackSoon": "Check back soon for updates!",
      "previousPage": "Previous page",
      "nextPage": "Next page",
      "page": "Page",
      "of": "of",
      "contact_subtitle": "Have questions about our vertical farming technology or want to learn more about our fresh vegetables? We'd love to hear from you.",
      "contact_us": "Send us a message",
      "name": "Name",
      "your_name": "Your name",
      "email": "Email",
      "your_email": "your@email.com",
      "subject": "Subject",
      "how_can_we_help": "How can we help you?",
      "message": "Message",
      "tell_us_more": "Tell us more about your inquiry...",
      "send_message": "Send Message",
      "sending": "Sending...",
      "back_to_products": "Back to Products",
      "featured": "Featured",
      "bestseller": "Bestseller",
      "in_stock": "In Stock",
      "out_of_stock": "Out of Stock",
      "add_to_cart": "Add to Cart",
      "hero_title1": "Fresh with",
      "hero_title2": "Living",
      "hero_title3": "Vegetables #1",
      "hero_description": "Discover the complex taste and crisp freshness of our living vegetables - grown with vertical farming technology!",
      "shop_now": "Shop now",
      "view_details": "View Details",
      "contact_information": "Contact Information",
      "address": "Address",
      "phone": "Phone",
      "business_hours": "Business Hours",
      "monday_to_friday": "Monday - Friday",
      "saturday": "Saturday",
      "sunday": "Sunday",
      "closed": "Closed",
      "facility_tours": "Facility Tours",
      "facility_tours_desc": "Interested in seeing our vertical farming technology in action? We offer guided tours of our facility to showcase our sustainable agriculture practices.",
      "schedule_tour": "Schedule a Tour",
      "footer_tagline": "Fresh living vegetables from vertical farming technology",
      "products": "Products",
      "top_sales": "Top Sales",
      "delivery": "Delivery",
      "returns": "Returns",
      "company": "Company",
      "privacy_policy": "Privacy Policy",
      "contact": "Contact",
      "all_rights_reserved": "All rights reserved.",
      "about_fresh_veggies_title": "Living Vegetables!",
      "about_fresh_veggies_desc1": "Skycrops is a vertical farming facility opening the doors to healthy living and fresh flavors. Our nutritious greens, grown indoors away from the negative effects of the outside world, bring taste and freshness to your table.",
      "about_fresh_veggies_desc2": "By applying the farming methods of the future today, Skycrops aims to bring you natural and fresh alternatives for a healthy life. The key to healthy living is hidden in Skycrops' greens.",
      "about_feature_fresh_title": "Fresh, Healthy",
      "about_feature_fresh_desc": "With our urban healthy farming model, products reach your table shortly after harvest, not after long transport or cold storage. Greens harvested with their roots are still alive when they arrive at your home and can keep growing under the right conditions. Grown in a clean, soilless environment, our greens are free from dust, soil, and pests, and are easy to clean.",
      "about_feature_fresh_icon1": "Daily\nHarvest",
      "about_feature_fresh_icon2": "On Your Table\nQuickly",
      "about_feature_fresh_icon3": "Effortless\nCleaning",
      "about_feature_safe_title": "Safe",
      "about_feature_safe_desc": "At Skycrops, our closed, controlled environment means we never use agricultural chemicals or hormones. Our carefully selected seeds grow healthy and strong with only the nutrients they need. That’s why Skycrops greens are completely safe!",
      "about_feature_safe_icon1": "Safe",
      "about_feature_safe_icon2": "Closed Growing\nEnvironment",
      "about_feature_safe_icon3": "Pesticide\nFree",
      "about_feature_safe_icon4": "Selected\nSeeds",
      "about_feature_tasty_title": "Tasty",
      "about_feature_tasty_desc": "At Skycrops, plants grow in optimal conditions for their biology, receiving the right nutrients, temperature, humidity, and light. Our top priority is growing 'happy plants.' The varieties we grow and select from seed are the same ones preferred by top chefs and restaurants worldwide.",
      "about_feature_tasty_icon1": "World\nFlavors",
      "about_feature_tasty_icon2": "Happy\nPlants",
      "about_feature_tasty_icon3": "Chef\nPreferred",
      "about_feature_tasty_icon4": "Rich\nNutrition",
      "about_feature_pesticide_title": "Pesticide Free",
      "about_feature_pesticide_desc": "No chemicals or hormones",
      "about_feature_eco_title": "Eco-friendly",
      "about_feature_eco_desc": "97% less water usage",
      "about_feature_living_title": "Living Vegetables",
      "about_feature_living_desc": "Living until consumption",
      "about_feature_grid_fresh_desc": "With our urban healthy farming concept, products do not undergo long transportation. Greens harvested with their roots are alive and continue to grow.",
      "about_feature_grid_pesticide_desc": "We use no agricultural chemicals or hormones thanks to our closed production environment with optimal conditions.",
      "about_feature_grid_eco_desc": "We use up to 97% less water than traditional farming. Solar panels and energy management technologies ensure sustainability.",
      "about_facility_title": "Skycrops Production Facility",
      "about_facility_desc": "In our 650 square meter net production area, we produce and harvest year-round with 84 eight-tier vertical farming units.",
      "about_facility_area_title": "Production Area",
      "about_facility_area_desc": "In our 650 sqm net production area, we produce and harvest year-round with 84 eight-tier vertical farming units. This way, we deliver fresh products to consumers all year round.",
      "about_facility_tech_title": "Technology",
      "about_facility_tech_desc": "Thanks to superior Farmicca grow LEDs, climate control, fertilizer dosing, and energy management technology, our plants grow as happy and healthy as in their natural environment.",
      "about_facility_pack_title": "Packaging & Shipping",
      "about_facility_pack_desc": "Our integrated, hygienic packaging and shipping area ensures vegetables reach consumers as quickly as possible after leaving the production facility.",
      "about_facility_energy_title": "Green Energy",
      "about_facility_energy_desc": "With 1 mW solar panels and rainwater harvesting, our energy management technologies make respect for nature our top principle.",
      "quality_policy": "Quality and Food Safety Policy",
      "loading_products": "Loading products...",
      "product_type": "Product Type",
      "all_products": "All Products",
      "no_products_found": "No products found for the selected category.",
      "view_all_products": "View All Products",
      "cart_empty_title": "Cart is empty",
      "cart_empty_description": "Add some products before checking out.",
      "checkout_not_implemented_title": "Checkout not implemented",
      "checkout_not_implemented_description": "This is a demo. Checkout functionality would be implemented here.",
      "shopping_cart": "Shopping Cart",
      "cart_empty": "Your cart is empty",
      "cart_items": "{{count}} item{{count > 1 ? 's' : ''}} in your cart",
      "total": "Total:",
      "checkout": "Checkout",
      "clear_cart": "Clear Cart",
      "added_to_cart": "Added to cart",
      "added_to_cart_description": "{{name}} added to your cart.",
      "flavor": "Flavor",
      "newsletter_success_title": "Success!",
      "newsletter_success_description": "You've been subscribed to our newsletter. Check your email for a discount code!",
      "newsletter_error_title": "Error",
      "newsletter_error_description": "Failed to subscribe. Please try again.",
      "newsletter_subtitle": "Your first order + future harvest updates. You can safely unsubscribe anytime.",
      "newsletter_email_placeholder": "Enter your email",
      "newsletter_subscribing": "Subscribing...",
      "newsletter_subscribe": "Subscribe",
      "newsletter_privacy_prefix": "Here is our",
      "plan_one_time": "One-time Purchase",
      "plan_one_time_desc": "Single delivery",
      "plan_weekly": "Weekly Subscription",
      "plan_weekly_desc": "Delivered every week",
      "plan_monthly": "Monthly Subscription",
      "plan_monthly_desc": "Delivered every month",
      "plan_yearly": "Yearly Subscription",
      "plan_yearly_desc": "Delivered every year",
      "delivery_express": "Express Delivery",
      "delivery_express_desc": "Same day delivery",
      "delivery_express_time": "Within 6 hours",
      "delivery_standard": "Standard Delivery",
      "delivery_standard_desc": "Next day delivery",
      "delivery_standard_time": "1-2 business days",
      "delivery_scheduled": "Scheduled Delivery",
      "delivery_scheduled_desc": "Choose your preferred day",
      "delivery_scheduled_time": "3-5 business days",
      "free": "Free",
      "recurring_plan": "Recurring {{plan}} • Cancel anytime",
      "footer_address": "Çorlu 1 OSB Bülent Ecevit Caddesi No:13/1\nPK: 59860 Çorlu – Tekirdağ",
      "footer_phone": "90 282 685 43 83",
      "footer_email": "info@skycrops.farm",
      "newsletter_heading": "GET 20% OFF",
      "follow_us": "Follow Us",
      "all_products_footer": "All Products",
      "bundles_footer": "Bundles",
      "blog_press_heading": "Blog - In the Press",
      "bundles_heading": "Vegetable Bundles",
      "bundles_subheading": "Curated collections of our freshest vegetables, perfectly paired for your healthy lifestyle",
      "save_percent": "Save {{percent}}%",
      "choose_delivery": "Choose Delivery",
      "choose_vegetables": "Choose your vegetables",
      "all_categories": "All categories",
      "category_leafy-greens_name": "Leafy Greens",
      "category_leafy-greens_desc": "Fresh, crisp leafy vegetables grown in our vertical farms",
      "category_fresh-herbs_name": "Herbs",
      "category_fresh-herbs_desc": "Aromatic herbs perfect for cooking and garnishing",
      "category_microgreens_name": "Microgreens",
      "category_microgreens_desc": "Nutrient-dense microgreens with intense flavors",
      "category_specialty-mix_name": "Specialty Mix",
      "category_specialty-mix_desc": "Curated combinations for balanced nutrition and taste",
      "product_living-lettuce-2_desc": "Fresh, crisp lettuce grown in our controlled environment. Perfect for salads and sandwiches.",
      "product_leafy-greens_desc": "Fresh, crisp leafy vegetables grown in our vertical farms.",
      "product_fresh-herbs_desc": "Aromatic herbs perfect for cooking and garnishing.",
      "product_microgreens_desc": "Nutrient-dense microgreens with intense flavors.",
      "admin_panel_title": "Admin Panel",
      "articles_tab": "Articles",
      "products_tab": "Products",
      "manage_articles_title": "Manage Articles",
      "manage_products_title": "Manage Products",
      "new_article_button": "New Article",
      "new_product_button": "New Product",
      "edit_article_title": "Edit Article",
      "create_new_article_title": "Create New Article",
      "edit_product_title": "Edit Product",
      "create_new_product_title": "Create New Product",
      "title_label": "Title",
      "slug_label": "Slug",
      "excerpt_label": "Excerpt",
      "content_label": "Content",
      "image_url_label": "Image URL",
      "published_date_label": "Published Date",
      "price_label": "Price",
      "category_label": "Category",
      "description_label": "Description",
      "featured_label": "Featured",
      "bestseller_label": "Bestseller",
      "in_stock_label": "In Stock",
      "saving_text": "Saving...",
      "update_button": "Update",
      "create_button": "Create",
      "cancel_button": "Cancel",
      "article_created_successfully": "Article created successfully!",
      "failed_to_create_article": "Failed to create article.",
      "article_updated_successfully": "Article updated successfully!",
      "failed_to_update_article": "Failed to update article.",
      "article_deleted_successfully": "Article deleted successfully!",
      "failed_to_delete_article": "Failed to delete article.",
      "product_created_successfully": "Product created successfully!",
      "failed_to_create_product": "Failed to create product.",
      "product_updated_successfully": "Product updated successfully!",
      "failed_to_update_product": "Failed to update product.",
      "product_deleted_successfully": "Product deleted successfully!",
      "failed_to_delete_product": "Failed to delete product.",
      "published_date": "Published Date",
      "price": "Price",
      "category": "Category",
      // Product Names
      "product_kivircik_name": "Curly Lettuce",
      "product_feslegen_name": "Basil",
      "product_maydanoz_name": "Parsley",
      "product_lollo_rosso_name": "Lollo Rosso",
      "product_reyhan_name": "Purple Basil",
      "product_roka_name": "Arugula",
      "product_kekik_name": "Thyme",
      "product_yagli_yaprak_name": "Butterhead Lettuce",
      // Bundle Names & Descriptions
      "bundle_fresh_greens_name": "Fresh Greens Bundle",
      "bundle_fresh_greens_desc": "Curly lettuce, arugula, and fresh products from our facility.",
      "bundle_garden_mix_name": "Small Family Bundle",
      "bundle_garden_mix_desc": "Curly lettuce, arugula, and fresh products from our facility.",
      "bundle_family_pack_name": "Large Family Bundle",
      "bundle_family_pack_desc": "Curly lettuce, arugula, and fresh products from our facility.",
      "production_facility_title": "Skycrops Production Facility",
      "production_facility_image_alt": "Skycrops production facility area",
      "production_area_title": "Production Area",
      "production_area_desc": "In our 650 sqm net production area, we produce and harvest year-round with 84 eight-tier vertical farming units. This way, we deliver fresh products to consumers all year round.",
      "packaging_shipping_title": "Packaging & Shipping",
      "packaging_shipping_desc": "Our integrated, hygienic packaging and shipping area ensures vegetables reach consumers as quickly as possible after leaving the production facility. Products harvested from our urban facility reach your table without losing freshness.",
      "technology_title": "Technology",
      "technology_desc": "Thanks to superior Farmicca grow LEDs, climate control, fertilizer dosing, and energy management technology, our plants grow as happy and healthy as in their natural environment.",
      "green_energy_title": "Green Energy",
      "green_energy_desc": "With 1 mW solar panels and rainwater harvesting, our energy management technologies make respect for nature our top principle. Skycrops vegetables use 94% less water than traditional farming.",
      "iso_certificate_alt": "ISO Certificate",
      "farmicca_note": "Skycrops facility installation and technology infrastructure provider",
      "contact_us_header": "Send Us a Message",
      "about_header": "About Us",
    }
  },
  tr: {
    translation: {
      "shop": "Mağaza",
      "about_us": "Hakkımızda",
      "blog": "Blog",
      "contacts": "İletişim",
      "home": "Anasayfa",
      "read_all_stories": "Tüm hikayeleri oku",
      "more_articles": "Daha fazla makale",
      "loading": "Yükleniyor...",
      "not_found": "Bulunamadı",
      "about_hero": "Dikey tarım teknolojisiyle tarımı devrimleştiriyoruz, size en taze ve en sağlıklı sebzeleri sunarken gezegenimizi koruyoruz.",
      "philosophy": "Felsefemiz",
      "about_philosophy": "Dünyayı birlikte daha sağlıklı yapalım. Skycrops olarak, taze ve canlı sebzeler sunmanın yanı sıra çevremizi korumanın da sorumluluğumuz olduğuna inanıyoruz. Bu yüzden devrim niteliğindeki dikey tarım teknolojimizi gururla sunuyoruz - her premium sebze alışınızda daha sürdürülebilir bir gelecek yaratmaya yardımcı oluyorsunuz!",
      "readArticle": "Makaleyi oku",
      "noArticles": "Şu anda mevcut makale yok.",
      "checkBackSoon": "Güncellemeler için tekrar kontrol edin!",
      "previousPage": "Önceki sayfa",
      "nextPage": "Sonraki sayfa",
      "page": "Sayfa",
      "of": "/",
      "contact_subtitle": "Dikey tarım teknolojimiz hakkında sorularınız mı var veya taze sebzelerimiz hakkında daha fazla bilgi mi almak istiyorsunuz? Sizden haber almak isteriz.",
      "contact_us": "Bize mesaj gönderin",
      "name": "İsim",
      "your_name": "Adınız",
      "email": "E-posta",
      "your_email": "eposta@adresiniz.com",
      "subject": "Konu",
      "how_can_we_help": "Size nasıl yardımcı olabiliriz?",
      "message": "Mesaj",
      "tell_us_more": "Talebiniz hakkında daha fazla bilgi verin...",
      "send_message": "Mesaj Gönder",
      "sending": "Gönderiliyor...",
      "back_to_products": "Ürünlere Dön",
      "featured": "Öne Çıkan",
      "bestseller": "Çok Satan",
      "in_stock": "Stokta Var",
      "out_of_stock": "Stokta Yok",
      "add_to_cart": "Sepete Ekle",
      "hero_title1": "Tazelikle",
      "hero_title2": "Canlı",
      "hero_title3": "Güvenli Sebzeler",
      "hero_description": "Skycrops, sağlıklı yaşamın ve taze lezzetlerin kapılarını aralayan bir dikey tarım tesisi. Doğallıktan uzaklaşmadan, kapalı ortamda, dış dünyanın negatif etkilerinden uzakta üretilen besleyici yeşilliklerimiz, sofralarınıza lezzet ve tazelik getiriyor. Skycrops, geleceğin tarım yöntemlerini bugün uygulayarak, sizleri sağlıklı bir yaşam için doğal ve taze alternatiflerle buluşturmayı hedefliyor. Sağlıklı yaşamın anahtarı, Skycrops'un yeşilliklerinde gizli.",
      "shop_now": "Alışverişe Başla",
      "view_details": "Detayları Gör",
      "contact_information": "İletişim Bilgileri",
      "address": "Adres",
      "phone": "Telefon",
      "business_hours": "Çalışma Saatleri",
      "monday_to_friday": "Pazartesi - Cuma",
      "saturday": "Cumartesi",
      "sunday": "Pazar",
      "closed": "Kapalı",
      "facility_tours": "Tesis Turları",
      "facility_tours_desc": "Dikey tarım teknolojimizi yerinde görmek ister misiniz? Sürdürülebilir tarım uygulamalarımızı göstermek için rehberli tesis turları sunuyoruz.",
      "schedule_tour": "Tur Planla",
      "footer_tagline": "Dikey tarım teknolojisinden taze yaşayan sebzeler",
      "products": "Ürünler",
      "top_sales": "Çok Satanlar",
      "delivery": "Teslimat",
      "returns": "İadeler",
      "company": "Şirket",
      "privacy_policy": "Gizlilik Politikası",
      "contact": "İletişim",
      "all_rights_reserved": "Tüm hakları saklıdır.",
      "about_fresh_veggies_title": "Yaşayan Sebzeler!",
      "about_fresh_veggies_desc1": "Skycrops, sağlıklı yaşamın ve taze lezzetlerin kapılarını aralayan bir dikey tarım tesisi. Doğallıktan uzaklaşmadan, kapalı ortamda, dış dünyanın negatif etkilerinden uzakta üretilen besleyici yeşilliklerimiz, sofralarınıza lezzet ve tazelik getiriyor.",
      "about_fresh_veggies_desc2": "Skycrops, geleceğin tarım yöntemlerini bugün uygulayarak, sizleri sağlıklı bir yaşam için doğal ve taze alternatiflerle buluşturmayı hedefliyor. Sağlıklı yaşamın anahtarı, Skycrops'un yeşilliklerinde gizli.",
      "about_feature_fresh_title": "Taze, Sağlıklı",
      "about_feature_fresh_desc": "Her gün taze hasat",
      "about_feature_pesticide_title": "Pestisit İçermez",
      "about_feature_pesticide_desc": "Hiçbir kimyasal veya hormon yok",
      "about_feature_eco_title": "Çevre Dostu",
      "about_feature_eco_desc": "%97 daha az su kullanımı",
      "about_feature_living_title": "Yaşayan Sebzeler",
      "about_feature_living_desc": "Tüketilene kadar canlı",
      "about_feature_grid_fresh_desc": "Şehir içi sağlıklı tarım konseptiyle üretim modelinde ürünler uzun nakliye süreçlerine girmez. Kökleriyle birlikte hasat edilen yeşillikler canlıdır ve büyümeye devam ederler.",
      "about_feature_grid_pesticide_desc": "Dış dünyanın negatif etkilerine kapalı üretim ortamında, optimum koşullarda üretim yaptığımız için hiç bir tarımsal ilaç ve hormon kullanmıyoruz.",
      "about_feature_grid_eco_desc": "Geleneksel tarım yöntemlerine göre %97'ye varan oranlarda daha az su tüketiyoruz. Güneş panelleri ve enerji yönetim teknolojileri ile sürdürülebilirliği sağlıyoruz.",
      "about_facility_title": "skycrops üretim tesisi",
      "about_facility_desc": "650 metrekare net üretim alanımızda 84 adet 8 katlı dikey tarım ünitesiyle yıl boyunca üretim ve hasat yapıyoruz.",
      "about_facility_area_title": "üretim alanı",
      "about_facility_area_desc": "650 metrekare net üretim alanımızda 84 adet 8 katlı dikey tarım ünitesiyle yıl boyunca üretim ve hasat yapıyoruz. Bu sayede yıl boyunca taze ürünleri tüketiciyle buluşturuyoruz.",
      "about_facility_tech_title": "teknoloji",
      "about_facility_tech_desc": "Üstün Farmicca büyütme ledleri, iklim kontrol, gübre dozajlama ve enerji yönetim teknolojisi sayesinde bitkilerimiz doğal ortamlarında olduğu kadar mutlu ve sağlıklı büyüyor.",
      "about_facility_pack_title": "paketleme ve sevkiyat",
      "about_facility_pack_desc": "Üretim alanıyla bütünleşik, hijyenik paketleme ve sevkiyat alanı sebzelerin üretim tesisinden çıktıktan sonra mümkün olan en hızlı sürede tüketiciyle buluşmasını sağlıyor.",
      "about_facility_energy_title": "yeşil enerji",
      "about_facility_energy_desc": "Kurulu 1 mW güneş panelleri ve yağmur hasadı, kullandığımız enerji yönetim teknolojileri sayesinde doğaya saygı en önemli prensibimiz.",
      "quality_policy": "Kalite ve Gıda Güvenliği Politikası",
      "loading_products": "Ürünler yükleniyor...",
      "product_type": "Ürün Türü",
      "all_products": "Tüm Ürünler",
      "no_products_found": "Seçilen kategori için ürün bulunamadı.",
      "view_all_products": "Tüm Ürünleri Gör",
      "cart_empty_title": "Sepet boş",
      "cart_empty_description": "Ödeme yapmadan önce ürün ekleyin.",
      "checkout_not_implemented_title": "Ödeme uygulanmadı",
      "checkout_not_implemented_description": "Bu bir demodur. Ödeme işlevi burada uygulanacaktır.",
      "shopping_cart": "Alışveriş Sepeti",
      "cart_empty": "Sepetiniz boş",
      "cart_items": "Sepetinizde {{count}} ürün var",
      "total": "Toplam:",
      "checkout": "Ödeme Yap",
      "clear_cart": "Sepeti Temizle",
      "added_to_cart": "Sepete eklendi",
      "added_to_cart_description": "{{name}} sepetinize eklendi.",
      "flavor": "Aroma",
      "newsletter_success_title": "Başarılı!",
      "newsletter_success_description": "Bültenimize abone oldunuz. İndirim kodu için e-postanızı kontrol edin!",
      "newsletter_error_title": "Hata",
      "newsletter_error_description": "Abonelik başarısız oldu. Lütfen tekrar deneyin.",
      "newsletter_subtitle": "İlk siparişiniz + gelecek hasat güncellemeleri. İstediğiniz zaman güvenle abonelikten çıkabilirsiniz.",
      "newsletter_email_placeholder": "E-posta adresinizi girin",
      "newsletter_subscribing": "Abone olunuyor...",
      "newsletter_subscribe": "Abone Ol",
      "newsletter_privacy_prefix": "İşte gizlilik politikamız",
      "plan_one_time": "Tek Seferlik Satın Alma",
      "plan_one_time_desc": "Tek teslimat",
      "plan_weekly": "Haftalık Abonelik",
      "plan_weekly_desc": "Her hafta teslimat",
      "plan_monthly": "Aylık Abonelik",
      "plan_monthly_desc": "Her ay teslimat",
      "plan_yearly": "Yıllık Abonelik",
      "plan_yearly_desc": "Her yıl teslimat",
      "delivery_express": "Ekspres Teslimat",
      "delivery_express_desc": "Aynı gün teslimat",
      "delivery_express_time": "6 saat içinde",
      "delivery_standard": "Standart Teslimat",
      "delivery_standard_desc": "Ertesi gün teslimat",
      "delivery_standard_time": "1-2 iş günü",
      "delivery_scheduled": "Planlı Teslimat",
      "delivery_scheduled_desc": "Tercih ettiğiniz günü seçin",
      "delivery_scheduled_time": "3-5 iş günü",
      "free": "Ücretsiz",
      "recurring_plan": "Yinelenen {{plan}} • İstediğiniz zaman iptal edin",
      "footer_address": "Çorlu 1 OSB Bülent Ecevit Caddesi No:13/1\nPK: 59860 Çorlu – Tekirdağ",
      "footer_phone": "90 282 685 43 83",
      "footer_email": "info@skycrops.farm",
      "newsletter_heading": "%20 İNDİRİM KAZAN",
      "follow_us": "Bizi Takip Edin",
      "all_products_footer": "Tüm Ürünler",
      "bundles_footer": "Paketler",
      "blog_press_heading": "Blog - Basında Biz",
      "bundles_heading": "Sebze Paketleri",
      "bundles_subheading": "En taze sebzelerimizin özenle seçilmiş koleksiyonları, sağlıklı yaşamınız için mükemmel şekilde eşleştirildi",
      "save_percent": "%{{percent}} İndirim",
      "choose_delivery": "Teslimat Seç",
      "choose_vegetables": "Sebzelerinizi seçin",
      "all_categories": "Tüm kategoriler",
      "category_leafy-greens_name": "Yapraklı Yeşillikler",
      "category_leafy-greens_desc": "Dikey çiftliklerimizde yetiştirilen taze, çıtır yeşillikler",
      "category_fresh-herbs_name": "Otlar",
      "category_fresh-herbs_desc": "Yemek ve süsleme için mükemmel aromatik otlar",
      "category_microgreens_name": "Mikro Yeşillikler",
      "category_microgreens_desc": "Yoğun aromalı, besin dolu mikro yeşillikler",
      "category_specialty-mix_name": "Özel Karışım",
      "category_specialty-mix_desc": "Dengeli beslenme ve lezzet için özenle seçilmiş karışımlar",
      // Product Names
      "product_kivircik_name": "Kıvırcık",
      "product_feslegen_name": "Fesleğen",
      "product_maydanoz_name": "Maydanoz",
      "product_lollo_rosso_name": "Lollo Rosso",
      "product_reyhan_name": "Reyhan",
      "product_roka_name": "Roka",
      "product_kekik_name": "Kekik",
      "product_yagli_yaprak_name": "Yağlı Yaprak",
      // Bundle Names & Descriptions
      "bundle_fresh_greens_name": "Taze Yeşillikler Paketi",
      "bundle_fresh_greens_desc": "Kıvırcık, roka ve tesisimizden taze ürünler.",
      "bundle_garden_mix_name": "Küçük Aile Paketi",
      "bundle_garden_mix_desc": "Kıvırcık, roka ve tesisimizden taze ürünler.",
      "bundle_family_pack_name": "Büyük Aile Paketi",
      "bundle_family_pack_desc": "Kıvırcık, roka ve tesisimizden taze ürünler.",
      "production_facility_title": "Skycrops Üretim Tesisi",
      "production_facility_image_alt": "Skycrops üretim tesisi alanı",
      "production_area_title": "Üretim Alanı",
      "production_area_desc": "650 metrekare net üretim alanımızda 84 adet 8 katlı dikey tarım ünitesiyle yıl boyunca üretim ve hasat yapıyoruz. Bu sayede yıl boyunca taze ürünleri tüketiciyle buluşturuyoruz.",
      "packaging_shipping_title": "Paketleme ve Sevkiyat",
      "packaging_shipping_desc": "Üretim alanıyla bütünleşik, hijyenik paketleme ve sevkiyat alanı sebzelerin üretim tesisinden çıktıktan sonra mümkün olan en hızlı sürede tüketiciyle buluşturmasını sağlıyor. Şehir içinde yerleşik üretim tesisimizden toplanan ürünler zaman kaybetmeden tazeliklerini koruyarak sofralara ulaşıyor.",
      "technology_title": "Teknoloji",
      "technology_desc": "Üstün Farmicca büyütme ledleri, iklim kontrol, gübre dozajlama ve enerji yönetim teknolojisi sayesinde bitkilerimiz doğal ortamlarında olduğu kadar mutlu ve sağlıklı büyüyor.",
      "green_energy_title": "Yeşil Enerji",
      "green_energy_desc": "Kurulu 1 mW güneş panelleri ve yağmur hasadı, kullandığımız enerji yönetim teknolojileri sayesinde doğaya saygı en önemli prensibimiz. Skycrops'ta yetiştirilen sebzeler geleneksel tarım yöntemlerine göre %94 daha az su tüketerek su kaynaklarının verimli kullanıyoruz.",
      "iso_certificate_alt": "ISO Sertifikası",
      "farmicca_note": "Skycrops tesis kurulumu ve teknoloji altyapısı sağlayıcısı",
      "contact_us_header": "Bize Mesaj Gönderin",
      "about_header": "Hakkımızda",
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'tr',
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
  });

createRoot(document.getElementById("root")!).render(<App />);
